package com.vcwdfca.ae2ct.mixin;

import appeng.api.stacks.KeyCounter;
import appeng.crafting.CraftingTreeNode;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Accessor;

/**
 * Exposes AE2's in-progress crafting calculation state to the AE2CT tree capture mixin.
 *
 * <p>The calculation owns the root tree and missing item counter. AE2CT needs those values
 * after a plan is produced so the client can render the same dependency tree.</p>
 */
@Mixin(value = appeng.crafting.CraftingCalculation.class, remap = false)
public interface AccessorCraftingCalculation {
    /**
     * Returns the root AE2 crafting tree node generated by the calculation.
     */
    @Accessor("tree")
    CraftingTreeNode ae2ct$getTree();

    /**
     * Returns the missing item counts accumulated while calculating the plan.
     */
    @Accessor("missing")
    KeyCounter ae2ct$getMissing();
}
